services:
  - type: web
    name: hub
    env: docker
    rootDir: notification-hub
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: routed-postgres
          property: connectionString
      - key: REDIS_URL
        value: "rediss://default:Aa5IAAIncDE4OTBjOGI1MzAzZTI0ZTMxODk0MGVkNzU4ODAyOGFmMXAxNDQ2MTY@obliging-drum-44616.upstash.io:6379"
      - key: DEFAULT_TTL_SEC
        value: "86400"
      - key: HUB_ADMIN_TOKEN
        value: "33925b5f5b9a2bd3d5a01f2b5857ce73"
      - key: VAPID_PUBLIC
        value: "" # set your VAPID public key
      - key: VAPID_PRIVATE
        value: "" # set your VAPID private key
      - key: BASE_URL
        value: "https://routed.onrender.com"
      - key: APPLY_SCHEMA_ON_BOOT
        value: "true"

  - type: web
    name: playground
    env: node
    rootDir: playground
    plan: free
    autoDeploy: true
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: HUB_URL
        value: "https://routed.onrender.com"
      - key: HUB_ADMIN_TOKEN
        value: "33925b5f5b9a2bd3d5a01f2b5857ce73"

databases:
  - name: routed-postgres
    plan: free
    databaseName: notification_hub
    user: routed_user
